### ISSUE TITLE
PPC/s390 (be/native):  testcase asm/atomics-[load|store].js failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#11]
```
>out/s390x.release/d8 --test --random-seed=1476338298 --nohard-abort --nodead-code-elimination --nofold-constants --harmony-sharedarraybuffer test/mjsunit/mjsunit.js test/mjsunit/asm/atomics-load.js

test/mjsunit/asm/atomics-load.js:20: TypeError: [object Int8Array] is not an integer shared typed array.
    return load(MEM8, i)|0;
           ^
TypeError: [object Int8Array] is not an integer shared typed array.
    at load (<anonymous>)
    at loadi8 (test/mjsunit/asm/atomics-load.js:20:12)
    at testElementType (test/mjsunit/asm/atomics-load.js:71:20)
    at testElement (test/mjsunit/asm/atomics-load.js:79:3)
    at test/mjsunit/asm/atomics-load.js:90:1


>out/s390x.release/d8 --test --random-seed=1476338298 --nohard-abort --nodead-code-elimination --nofold-constants --harmony-sharedarraybuffer test/mjsunit/mjsunit.js test/mjsunit/asm/atomics-store.js

test/mjsunit/asm/atomics-store.js:21: TypeError: [object Int8Array] is not an integer shared typed array.
    return store(MEM8, i, x)|0;
           ^
TypeError: [object Int8Array] is not an integer shared typed array.
    at store (<anonymous>)
    at storei8 (test/mjsunit/asm/atomics-store.js:21:12)
    at testElementType (test/mjsunit/asm/atomics-store.js:76:20)
    at testElement (test/mjsunit/asm/atomics-store.js:84:3)
    at test/mjsunit/asm/atomics-store.js:95:1
```

**Comment by jbajwa** [comment]
fix for #12 applies for this issue as well.
