### ISSUE TITLE
s390x (sim): testcase failures

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#14]
82 testcases are failing on s390x (64bit) on sim build. The failure started after this CL https://codereview.chromium.org/2451973003

Some of the failures:
```
=== mjsunit/wasm/embenchen/memops ===
--- stdout ---
============ Stress 1/5 ============
/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221: Failure: expected <"final: 840.\n"> found <"final: 8589935432.\n">

Stack: Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8023:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8035:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8092:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8023:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8035:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8092:1
Command: /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/out/Release/d8 --test --random-seed=-400954096 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --validate-asm --allow-natives-syntax /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js
=== mjsunit/wasm/embenchen/zlib ===
--- stdout ---
============ Stress 1/5 ============
/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221: Failure: expected <"sizes: 100000,25906\nok.\n"> found <"sizes: 8590034592,8589960498\nok.\n">

Stack: Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:14688:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:14700:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:14757:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:14688:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:14700:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js:14757:1
Command: /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/out/Release/d8 --test --random-seed=-400954096 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --validate-asm --allow-natives-syntax /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/zlib.js
=== mjsunit/wasm/embenchen/lua_binarytrees ===
--- stdout ---
============ Stress 1/5 ============
/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221: Failure: expected <"stretch tree of depth 10\t check: -1\n1448\t trees of depth 4\t check: -1448\n362\t trees of depth 6\t check: -362\n90\t trees of depth 8\t check: -90\nlong lived tree of depth 9\t check: -1\n"> found <"stretch tree of depth 8589934602\t check: -1\n8589936040\t trees of depth 8589934596\t check: -1448\n8589934954\t trees of depth 8589934598\t check: -362\n8589934682\t trees of depth 8589934600\t check: -90\nlong lived tree of depth 8589934601\t check: -1\n">

Stack: Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:15:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1159:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1216:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42646:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42658:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42715:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:15:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1159:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1216:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42646:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42658:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42715:1
Command: /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/out/Release/d8 --test --random-seed=-400954096 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --validate-asm --allow-natives-syntax /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js
=== mjsunit/asm/embenchen/zlib ===
--- stdout ---
/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221: Failure: expected <"sizes: 100000,25906\nok.\n"> found <"sizes: 8590034592,8589960498\nok.\n">

Stack: Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:7:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:1124:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:1181:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:14683:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:14695:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:14752:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:7:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:1124:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:1181:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:14683:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:14695:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js:14752:1
Command: /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/out/Release/d8 --test --random-seed=-400954096 --turbo --nohard-abort --nodead-code-elimination --nofold-constants /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/asm/embenchen/zlib.js
=== mjsunit/wasm/embenchen/copy ===
--- stdout ---
============ Stress 1/5 ============
/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221: Failure: expected <"sum:8930\n"> found <"sum:8589943522\n">

Stack: Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:5912:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:5924:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:5981:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:5912:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:5924:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js:5981:1
Command: /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/out/Release/d8 --test --random-seed=-400954096 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --validate-asm --allow-natives-syntax /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/copy.js
=== mjsunit/wasm/embenchen/lua_binarytrees ===
--- stdout ---
============ Stress 1/5 ============
/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221: Failure: expected <"stretch tree of depth 10\t check: -1\n1448\t trees of depth 4\t check: -1448\n362\t trees of depth 6\t check: -362\n90\t trees of depth 8\t check: -90\nlong lived tree of depth 9\t check: -1\n"> found <"stretch tree of depth 8589934602\t check: -1\n8589936040\t trees of depth 8589934596\t check: -1448\n8589934954\t trees of depth 8589934598\t check: -362\n8589934682\t trees of depth 8589934600\t check: -90\nlong lived tree of depth 8589934601\t check: -1\n">

Stack: Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:15:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1159:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1216:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42646:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42658:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42715:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:15:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1159:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:1216:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42646:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42658:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js:42715:1
Command: /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/out/Release/d8 --test --random-seed=-400954096 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --validate-asm --allow-natives-syntax /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/lua_binarytrees.js
=== mjsunit/wasm/embenchen/memops ===
--- stdout ---
============ Stress 1/5 ============
/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221: Failure: expected <"final: 840.\n"> found <"final: 8589935432.\n">

Stack: Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8023:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8035:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8092:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js:292:7)
    at Module.postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:10:5)
    at callRuntimeCallbacks (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1127:7)
    at postRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:1184:3)
    at doRun (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8023:5)
    at run (/mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8035:5)
    at /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js:8092:1
Command: /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/out/Release/d8 --test --random-seed=-400954096 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --validate-asm --allow-natives-syntax /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/mjsunit.js /mnt/data/b/build/slave/V8_Linux_-_s390x_-_sim/build/v8/test/mjsunit/wasm/embenchen/memops.js
```

**Comment by jbajwa** [comment]
Investigating one of the testcase, **int32mod-constant.js.**
So far I've got:
Math.abs is not working as expected on s390x. Running this js snippet with d8 can reproduce the issue, moreover with snapshot off the issue is gone.
```
> out/s390x.release/d8 abs.js
-2147483648  // (should be 2147483648)
>cat abs.js
print(Math.abs(-2147483648))
```
Gets the absolute value of any other negative number correctly. Only fails for -2147483648 which is the min value for a signed int32. Only affects s390x sim builds with snapshot on.

**Comment by jbajwa** [comment]
https://codereview.chromium.org/2446113013
The issue was that the logic to detect INT_MIN in 64bit was incorrect.
