### ISSUE TITLE
s390: testcase regress-crbug-663402.js failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#18]
```
>out/s390x.release/d8 --test --random-seed=-738761535 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax test/mjsunit/mjsunit.js  test/mjsunit/regress/regress-crbug-663402.js

test/mjsunit/mjsunit.js:221: Failure: expected <0.1> found <0>

Stack: Error
    at new MjsUnitAssertionError (/local/jbajwa/google_v8_2/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/local/jbajwa/google_v8_2/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/local/jbajwa/google_v8_2/v8/test/mjsunit/mjsunit.js:292:7)
    at /local/jbajwa/google_v8_2/v8/test/mjsunit/regress/regress-crbug-663402.js:34:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/local/jbajwa/google_v8_2/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/local/jbajwa/google_v8_2/v8/test/mjsunit/mjsunit.js:221:11)
    at assertEquals (/local/jbajwa/google_v8_2/v8/test/mjsunit/mjsunit.js:292:7)
    at /local/jbajwa/google_v8_2/v8/test/mjsunit/regress/regress-crbug-663402.js:34:3
```

**Comment by jbajwa** [comment]
@john-yan Thanks.
https://codereview.chromium.org/2492913002/

**Comment by joransiu** [comment]
@jbajwa @john-yan: is this something we need to backport to beta/stable and cherry-pick over to Node.js V6.x?

**Comment by jbajwa** [comment]
@joransiu Hi Joran, yes I believe this fix should apply to beta/stable as well. This got exposed only now with this new testcase.
@john-yan do you agree?
