### ISSUE TITLE
PPC/s390 (native): testcase regress-3025 failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#22]
```
> out/Release/d8 --test --random-seed=2031542058 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/regress/regress-3025.js

test/mjsunit/mjsunit.js:225: Failure: expected <9223372036854778000> found <2951479051793529>

Stack: Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:225:11)
    at assertEquals (test/mjsunit/mjsunit.js:296:7)
    at test/mjsunit/regress/regress-3025.js:32:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:225:11)
    at assertEquals (test/mjsunit/mjsunit.js:296:7)
    at test/mjsunit/regress/regress-3025.js:32:1
```
first bad commit : https://codereview.chromium.org/2520363002

**Comment by jbajwa** [comment]
the testcase was fixed under https://codereview.chromium.org/2526223003
