### ISSUE TITLE
PPC64: wasm/asm-wasm-switch.js failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#24]
```
>out/ppc64.release/d8 --test --random-seed=-976563914 --validate-asm --nohard-abort --nodead-code-elimination --nofold-constants --validate-asm --allow-natives-syntax test/mjsunit/mjsunit.js test/mjsunit/wasm/asm-wasm-switch.js

test/mjsunit/mjsunit.js:225: Failure: expected <-2147483648> found <-1>

Stack: Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:225:11)
    at assertEquals (test/mjsunit/mjsunit.js:296:7)
    at TestLargeSwitch (test/mjsunit/wasm/asm-wasm-switch.js:439:5)
    at test/mjsunit/wasm/asm-wasm-switch.js:486:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:225:11)
    at assertEquals (test/mjsunit/mjsunit.js:296:7)
    at TestLargeSwitch (test/mjsunit/wasm/asm-wasm-switch.js:439:5)
    at test/mjsunit/wasm/asm-wasm-switch.js:486:3

```
Bad commit https://codereview.chromium.org/2545463002

**Comment by jbajwa** [comment]
fix upstreamed https://codereview.chromium.org/2559433003/
