### ISSUE TITLE
PPC/s390: integral32-add-sub.js failing with snapshot=off

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#32]
```
> out/s390x.release/d8 --test --random-seed=1519407221 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax test/mjsunit/mjsunit.js test/mjsunit/compiler/integral32-add-sub.js

============ Stress 1/2 ============
============ Stress 2/2 ============
test/mjsunit/mjsunit.js:225: Failure: expected <2147483648> found <-2147483648>

Stack: Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:225:11)
    at assertEquals (test/mjsunit/mjsunit.js:296:7)
    at test/mjsunit/compiler/integral32-add-sub.js:77:3
    at test/mjsunit/compiler/integral32-add-sub.js:89:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:225:11)
    at assertEquals (test/mjsunit/mjsunit.js:296:7)
    at test/mjsunit/compiler/integral32-add-sub.js:77:3
    at test/mjsunit/compiler/integral32-add-sub.js:89:3
```

**Comment by jbajwa** [comment]
https://codereview.chromium.org/2639853002/
