### ISSUE TITLE
s390/PPC [BE]: es6/spread-call.js failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#35]
```
> out/s390x.release/d8 --test --random-seed=1183006409 --turbo --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/es6/spread-call.js

test/mjsunit/mjsunit.js:257: Failure: expected <10> found <NaN>

Stack: Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:257:11)
    at assertEquals (test/mjsunit/mjsunit.js:328:7)
    at testArrayPrototypeHoleGetterModifiesIteratorPrototypeNext (test/mjsunit/es6/spread-call.js:389:3)
    at test/mjsunit/es6/spread-call.js:393:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:257:11)
    at assertEquals (test/mjsunit/mjsunit.js:328:7)
    at testArrayPrototypeHoleGetterModifiesIteratorPrototypeNext (test/mjsunit/es6/spread-call.js:389:3)
    at test/mjsunit/es6/spread-call.js:393:3
```

**Comment by jbajwa** [comment]
https://codereview.chromium.org/2668303002/
Thanks @john-yan !
