### ISSUE TITLE
PPC/S390: regress-694088.js failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#38]
```
>out/ppc64.release/d8 --test --random-seed=-385268958 --ignition-staging --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/compiler/regress-694088.js
=== mjsunit/compiler/regress-694088 ===
test/mjsunit/mjsunit.js:254: Failure: expected <0> found <1072693248>

Stack: Error
    at new MjsUnitAssertionError (/home/jbajwa/ppcbe_v8_lnx/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:254:11)
    at assertEquals (test/mjsunit/mjsunit.js:325:7)
    at test/mjsunit/compiler/regress-694088.js:15:3
    at /test/mjsunit/compiler/regress-694088.js:16:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:254:11)
    at assertEquals (test/mjsunit/mjsunit.js:325:7)
    at test/mjsunit/compiler/regress-694088.js:15:3
    at test/mjsunit/compiler/regress-694088.js:16:3
```
Test case was added today in CL https://codereview.chromium.org/2725593002
Seems to be endianness related

**Comment by jbajwa** [comment]
The failure is expected behaviour on BigEndian, added suggestion in the original [CL](https://codereview.chromium.org/2725593002/) to fix the testcase.

**Comment by jbajwa** [comment]
fix under https://codereview.chromium.org/2739403002
