### ISSUE TITLE
PPC/S390: wasm/interpreter.js failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#42]
```
>out/ppc64.release/d8 --test --random-seed=-2025925132 --no-turbo --nohard-abort --nodead-code-elimination --nofold-constants --wasm-interpret-all --allow-natives-syntax test/mjsunit/mjsunit.js test/mjsunit/wasm/interpreter.js

test/mjsunit/mjsunit.js:251: Failure: expected <6> found <0>

Stack: Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at failWithMessage (test/mjsunit/mjsunit.js:251:11)
    at fail (test/mjsunit/mjsunit.js:268:12)
    at assertEquals (test/mjsunit/mjsunit.js:339:7)
    at testIndirectImports (test/mjsunit/wasm/interpreter.js:252:3)
    at test/mjsunit/wasm/interpreter.js:260:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at failWithMessage (test/mjsunit/mjsunit.js:251:11)
    at fail (test/mjsunit/mjsunit.js:268:12)
    at assertEquals (test/mjsunit/mjsunit.js:339:7)
    at testIndirectImports (test/mjsunit/wasm/interpreter.js:252:3)
    at test/mjsunit/wasm/interpreter.js:260:3
```
Started failing after https://chromium-review.googlesource.com/458417

**Comment by jbajwa** [comment]
fixed under https://chromium-review.googlesource.com/c/461859/
