### ISSUE TITLE
PPC: regress/regress-353551 testcase failing

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#6]
```
>out/d8 --test --random-seed=482085299 --ignition-staging --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/regress/regress-353551.js

test/mjsunit/regress/regress-353551.js:38: RangeError: Maximum call stack size exceeded
  __f_4();
  ^
RangeError: Maximum call stack size exceeded
    at __f_3 (test/mjsunit/regress/regress-353551.js:38:3)
    at __f_4 (test/mjsunit/regress/regress-353551.js:36:5)
    at __f_3 (test/mjsunit/regress/regress-353551.js:38:3)
    at __f_4 (test/mjsunit/regress/regress-353551.js:36:5)
    at __f_3 (test/mjsunit/regress/regress-353551.js:38:3)
    at __f_4 (test/mjsunit/regress/regress-353551.js:36:5)
    at __f_3 (test/mjsunit/regress/regress-353551.js:38:3)
    at __f_4 (test/mjsunit/regress/regress-353551.js:36:5)
    at __f_3 (test/mjsunit/regress/regress-353551.js:38:3)
    at __f_4 (test/mjsunit/regress/regress-353551.js:36:5)
```

**Comment by jbajwa** [comment]
The testcase passes with --stack-size=1100. But this fix might not agree with other platforms, similar to this issue https://codereview.chromium.org/2098413002.
Will open a CL to disable this testcase.
@joransiu @mhdawson

**Comment by jbajwa** [comment]
https://codereview.chromium.org/2314343002/
