### ISSUE TITLE
ppc/s390: string-iterator.js testcase failure (native, big endian)

### ISSUE THREAD

**Issue by jbajwa** [ibmruntimes/v8#9]
Looks like its an endianness issue. Testcase passes on ppcle.
```
out/ppc64.release/d8 --test --random-seed=1142934043 --ignition --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/es6/array-from.js
=== mjsunit/es6/array-from ===
test/mjsunit/mjsunit.js:216: Failure: expected <"�"> found <"��">

Stack: Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:216:11)
    at assertEquals (test/mjsunit/mjsunit.js:287:7)
    at assertArrayLikeEquals (test/mjsunit/es6/array-from.js:13:5)
    at testArrayFrom (test/mjsunit/es6/array-from.js:80:3)
    at test/mjsunit/es6/array-from.js:141:1
    at test/mjsunit/es6/array-from.js:178:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:216:11)
    at assertEquals (test/mjsunit/mjsunit.js:287:7)
    at assertArrayLikeEquals (test/mjsunit/es6/array-from.js:13:5)
    at testArrayFrom (test/mjsunit/es6/array-from.js:80:3)
    at test/mjsunit/es6/array-from.js:141:1
    at test/mjsunit/es6/array-from.js:178:3
```
Testcase was last update in CL https://codereview.chromium.org/2381053002

**Comment by jbajwa** [comment]
fix in master
https://codereview.chromium.org/2431223010/
and backported to 5.5
https://codereview.chromium.org/2443233002/
